# For Manager
manager:
  ip: 127.0.0.1
  external: 0

# For Coordinator
coordinator:
  coord_threads: 4
  io_threads: 2
  manager: 127.0.0.1
  ip:
    private: 127.0.0.1
    public: 127.0.0.1
  delay: 0

# For scheduler
scheduler:
  threads:
    coord: 4
    io: 2
  func_dir: /tmp/shm/
  delay: 0
  shared: 1
  forward_or_reject: 0
  user:
    ip: 127.0.0.1
    executor: 1
    routing-elb: 127.0.0.1
    coord:
      - 127.0.0.1

# For Executor
executor:
  func_dir: /tmp/shm/
  wait: 0
  ip: 127.0.0.1
  thread_id: 0